# Start with the official openjdk 11 image
FROM openjdk:11

# Skip the plug installation
ENV JAVA_OPTS="-Djenkins.install.runSetupWizard=false"

# Install basic tools
RUN apt-get update && \
    apt-get install -y curl unzip jq && \
    apt-get clean;

# Ensure permissions and fetch Jenkins WAR
RUN mkdir -p /usr/share/jenkins && \
    chmod 777 /usr/share/jenkins && \
    curl -fsSL https://get.jenkins.io/war-stable/latest/jenkins.war -o /usr/share/jenkins/jenkins.war

# Install Docker
RUN curl -fsSL https://get.docker.com -o get-docker.sh && \
    sh get-docker.sh && \
    apt-get clean;

# Install Gradle
RUN curl -LO https://services.gradle.org/distributions/gradle-7.2-bin.zip && \
    unzip gradle-7.2-bin.zip -d /opt && \
    rm gradle-7.2-bin.zip && \
    ln -s /opt/gradle-7.2/bin/gradle /usr/bin/gradle

# Validate the Gradle installation
RUN gradle -v

# Download and install jenkins-plugin-cli
RUN curl -L "https://github.com/jenkinsci/plugin-installation-manager-tool/releases/download/2.11.0/jenkins-plugin-manager-2.11.0.jar" -o /usr/local/bin/jenkins-plugin-manager.jar
RUN echo '#!/bin/sh' > /usr/local/bin/jenkins-plugin-cli && \
    echo 'java -jar /usr/local/bin/jenkins-plugin-manager.jar "$@"' >> /usr/local/bin/jenkins-plugin-cli && \
    chmod +x /usr/local/bin/jenkins-plugin-cli

# Copy the shell script into the Docker container
COPY ../run_local.sh /var/jenkins_home/run_local.sh
RUN chmod +x /var/jenkins_home/run_local.sh
RUN chmod +x /usr/local/bin/jenkins-plugin-cli

# Test: Install Jenkins plugins
COPY jenkins/plugins.txt /usr/share/jenkins/ref/plugins.txt
RUN jenkins-plugin-cli --plugin-file /usr/share/jenkins/ref/plugins.txt

# Copy the init.groovy script into the Docker image
COPY jenkins/init.groovy /usr/share/jenkins/ref/init.groovy.d/

# Ensure init.groovy is copied to JENKINS_HOME on container startup
RUN mkdir -p /root/.jenkins/init.groovy.d/ && cp /usr/share/jenkins/ref/init.groovy.d/* /root/.jenkins/init.groovy.d/

# Copy plugins.txt to JENKINS_HOME as well
RUN mkdir -p /root/.jenkins/ && cp /usr/share/jenkins/ref/plugins.txt /root/.jenkins/plugins.txt

# Command to run Jenkins
CMD ["java", "-jar", "/usr/share/jenkins/jenkins.war"]
